In [23]:
import numpy as np
import os
from PIL import Image
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score
from sklearn.model_selection import GridSearchCV

In [42]:
def loading_data(path):
  x = []
  y = []
  for brand in os.listdir(path):
    images = os.listdir(path + '/' + brand)
    for image in images:
      im = Image.open(path + '/' + brand + '/' + image)
      resize = im.resize((200,200))
      np_img = np.array(resize)
      # data = np.asarray(im)
      np_img = np_img.flatten()
      x.append(np_img)
      y.append(os.listdir(path).index(brand))
      #im.show()
  return x, y

In [43]:
train_path = 'Dataset/train'

In [8]:
shose_category = os.listdir(train_path)
shose_category

['adidas', 'converse', 'nike']

In [44]:
X_train, y_train = loading_data(train_path)

In [10]:
test_path = 'Dataset/test'

In [11]:
X_test, y_test = loading_data(test_path)

### Navie Bayes

In [1]:
from sklearn.naive_bayes import GaussianNB

c:\Users\Samuels\anaconda3\lib\site-packages\scipy\__init__.py:138: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.23.4)
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion} is required for this version of "


In [2]:
nb = GaussianNB()

In [14]:
param = {'var_smoothing': np.logspace(0,-9, num=20)}

In [15]:
grid = GridSearchCV(nb, param)

In [16]:
grid.fit(X_train, y_train)

GridSearchCV(estimator=GaussianNB(),
             param_grid={'var_smoothing': array([1.00000000e+00, 3.35981829e-01, 1.12883789e-01, 3.79269019e-02,
       1.27427499e-02, 4.28133240e-03, 1.43844989e-03, 4.83293024e-04,
       1.62377674e-04, 5.45559478e-05, 1.83298071e-05, 6.15848211e-06,
       2.06913808e-06, 6.95192796e-07, 2.33572147e-07, 7.84759970e-08,
       2.63665090e-08, 8.85866790e-09, 2.97635144e-09, 1.00000000e-09])})

In [17]:
print(grid.best_params_)

{'var_smoothing': 1.0}


In [18]:
nb = GaussianNB(var_smoothing= 1.0)

In [20]:
nb.fit(X_train, y_train)

GaussianNB(var_smoothing=1.0)

In [21]:
predictions = nb.predict(X_test)
predictions

array([2, 1, 2, 1, 1, 2, 1, 1, 1, 1, 1, 1, 2, 2, 2, 1, 1, 1, 1, 2, 2, 1,
       1, 2, 2, 1, 1, 1, 1, 1, 1, 2, 1, 1, 2, 2, 1, 1, 1, 2, 1, 2, 1, 1,
       1, 1, 2, 1, 1, 1, 1, 1, 2, 1, 1, 1, 2, 2, 1, 1, 1, 1, 2, 1, 1, 0,
       1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 2, 2, 1, 1, 2, 2, 2, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 2, 1, 1, 1, 1, 2, 2, 2, 1, 1, 2, 2,
       1, 2, 1, 2])

In [24]:
print(classification_report(y_test, predictions))

              precision    recall  f1-score   support

           0       0.00      0.00      0.00        38
           1       0.38      0.76      0.50        38
           2       0.42      0.39      0.41        38

    accuracy                           0.39       114
   macro avg       0.26      0.39      0.30       114
weighted avg       0.26      0.39      0.30       114



In [25]:
accuracy = accuracy_score(y_test, predictions)
accuracy

0.38596491228070173

### Logistic Regression

In [59]:
from sklearn.linear_model import LogisticRegression

In [ ]:
# logmodel = LogisticRegression(random_state=0, max_iter=50).fit(X_train, y_train)

In [9]:
logmodel = LogisticRegression()

In [10]:
param = {'max_iter': [50,100,150,200],
          'penalty':["l1","l2"]}

In [11]:
grid = GridSearchCV(logmodel, param)

In [12]:
grid.fit(X_train, y_train)

c:\Users\Samuels\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: 
Traceback (most recent call last):
  File "c:\Users\Samuels\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py", line 593, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "c:\Users\Samuels\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py", line 1306, in fit
    solver = _check_solver(self.solver, self.penalty, self.dual)
  File "c:\Users\Samuels\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py", line 443, in _check_solver
    raise ValueError("Solver %s supports only 'l2' or 'none' penalties, "
ValueError: Solver lbfgs supports only 'l2' or 'none' penalties, got l1 penalty.

  warnings.warn("Estimator fit failed. The score on this train-test"
c:\Users\Samuels\anaconda3\lib\site-packages\sklearn\model_se

GridSearchCV(estimator=LogisticRegression(),
             param_grid={'max_iter': [50, 100, 150, 200],
                         'penalty': ['l1', 'l2']})

In [13]:
print(grid.best_params_)

{'max_iter': 200, 'penalty': 'l2'}


In [14]:
logmodel = LogisticRegression(max_iter=200, penalty = 'l2').fit(X_train, y_train)

c:\Users\Samuels\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [15]:
predictions = logmodel.predict(X_test)
predictions

array([1, 2, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 2, 2, 0, 1, 0, 0, 1, 0, 2,
       0, 0, 2, 0, 1, 0, 2, 2, 1, 0, 2, 0, 1, 2, 1, 0, 0, 0, 2, 2, 1, 1,
       1, 1, 0, 1, 2, 0, 1, 0, 2, 1, 1, 2, 2, 1, 1, 1, 2, 2, 1, 2, 1, 0,
       1, 2, 2, 1, 2, 1, 1, 2, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 1, 0, 0,
       2, 2, 1, 2, 2, 0, 1, 0, 2, 2, 0, 1, 2, 2, 1, 2, 0, 2, 1, 2, 2, 2,
       2, 0, 0, 2])

In [16]:
print(classification_report(y_test, predictions))

              precision    recall  f1-score   support

           0       0.56      0.47      0.51        38
           1       0.51      0.50      0.51        38
           2       0.51      0.61      0.55        38

    accuracy                           0.53       114
   macro avg       0.53      0.53      0.53       114
weighted avg       0.53      0.53      0.53       114



In [17]:
accuracy = accuracy_score(y_test, predictions)
accuracy

0.5263157894736842

### Random Forest

In [18]:
from sklearn.ensemble import RandomForestClassifier

In [19]:
# rf = RandomForestClassifier(n_estimators=100,max_features = 'sqrt', n_jobs=-1, verbose = 1)

In [21]:
rf = RandomForestClassifier()

In [25]:
param = { 'criterion':['gini', 'entropy', 'log_loss'],
          'max_depth' : [3,4,5,6,7],
          'n_estimators' : [100,150,200]}

In [26]:
grid = GridSearchCV(rf, param)

In [27]:
grid.fit(X_train, y_train)

c:\Users\Samuels\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: 
Traceback (most recent call last):
  File "c:\Users\Samuels\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py", line 593, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "c:\Users\Samuels\anaconda3\lib\site-packages\sklearn\ensemble\_forest.py", line 387, in fit
    trees = Parallel(n_jobs=self.n_jobs, verbose=self.verbose,
  File "c:\Users\Samuels\anaconda3\lib\site-packages\joblib\parallel.py", line 1041, in __call__
    if self.dispatch_one_batch(iterator):
  File "c:\Users\Samuels\anaconda3\lib\site-packages\joblib\parallel.py", line 859, in dispatch_one_batch
    self._dispatch(tasks)
  File "c:\Users\Samuels\anaconda3\lib\site-packages\joblib\parallel.py", line 777, in _dispatch
    job = self._backend.apply_async(batch, 

GridSearchCV(estimator=RandomForestClassifier(),
             param_grid={'criterion': ['gini', 'entropy', 'log_loss'],
                         'max_depth': [3, 4, 5, 6, 7],
                         'n_estimators': [100, 150, 200]})

In [28]:
print(grid.best_params_)

{'criterion': 'gini', 'max_depth': 6, 'n_estimators': 200}


In [29]:
rf = RandomForestClassifier(criterion = 'gini', max_depth=6, n_estimators=200)

In [30]:
rf.fit(X_train, y_train)

RandomForestClassifier(max_depth=6, n_estimators=200)

In [31]:
predictions = rf.predict(X_test)

In [32]:
print(classification_report(y_test, predictions))

              precision    recall  f1-score   support

           0       0.62      0.42      0.50        38
           1       0.53      0.55      0.54        38
           2       0.50      0.63      0.56        38

    accuracy                           0.54       114
   macro avg       0.55      0.54      0.53       114
weighted avg       0.55      0.54      0.53       114



In [33]:
accuracy = accuracy_score(y_test, predictions)
accuracy

0.5350877192982456

### SVM

In [34]:
from sklearn.svm import SVC

In [35]:
svc = SVC()

In [36]:
param = {'C': [1, 5, 10, 50],
         'gamma': [0.0001, 0.0005, 0.001, 0.005]}

In [37]:
grid = GridSearchCV(svc, param)

In [38]:
grid.fit(X_train, y_train)

GridSearchCV(estimator=SVC(),
             param_grid={'C': [1, 5, 10, 50],
                         'gamma': [0.0001, 0.0005, 0.001, 0.005]})

In [39]:
print(grid.best_params_)

{'C': 1, 'gamma': 0.0001}


In [40]:
svc = SVC(C=1, gamma=0.0001)

In [41]:
svc.fit(X_train, y_train)

SVC(C=1, gamma=0.0001)

In [42]:
predictions = svc.predict(X_test)

In [43]:
print(classification_report(y_test, predictions))

              precision    recall  f1-score   support

           0       0.00      0.00      0.00        38
           1       0.00      0.00      0.00        38
           2       0.33      1.00      0.50        38

    accuracy                           0.33       114
   macro avg       0.11      0.33      0.17       114
weighted avg       0.11      0.33      0.17       114



c:\Users\Samuels\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\Samuels\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\Samuels\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [44]:
accuracy = accuracy_score(y_test, predictions)
accuracy

0.3333333333333333

#### Decision Tree

In [45]:
from sklearn.tree import DecisionTreeClassifier

In [46]:
tree = DecisionTreeClassifier()

In [47]:
param = {'criterion': ['gini', 'entropy', 'log_loss'],
         'max_depth': [3,4,5,6,7,8]}

In [48]:
grid = GridSearchCV(tree, param)

In [49]:
grid.fit(X_train, y_train)

c:\Users\Samuels\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: 
Traceback (most recent call last):
  File "c:\Users\Samuels\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py", line 593, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "c:\Users\Samuels\anaconda3\lib\site-packages\sklearn\tree\_classes.py", line 898, in fit
    super().fit(
  File "c:\Users\Samuels\anaconda3\lib\site-packages\sklearn\tree\_classes.py", line 347, in fit
    criterion = CRITERIA_CLF[self.criterion](self.n_outputs_,
KeyError: 'log_loss'

  warnings.warn("Estimator fit failed. The score on this train-test"
c:\Users\Samuels\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. D

GridSearchCV(estimator=DecisionTreeClassifier(),
             param_grid={'criterion': ['gini', 'entropy', 'log_loss'],
                         'max_depth': [3, 4, 5, 6, 7, 8]})

In [50]:
print(grid.best_params_)

{'criterion': 'gini', 'max_depth': 6}


In [51]:
tree = DecisionTreeClassifier(criterion='gini', max_depth=6)

In [52]:
tree.fit(X_train, y_train)

DecisionTreeClassifier(max_depth=6)

In [53]:
predictions = tree.predict(X_test)

In [54]:
print(classification_report(y_test, predictions))

              precision    recall  f1-score   support

           0       0.50      0.55      0.53        38
           1       0.50      0.55      0.53        38
           2       0.40      0.32      0.35        38

    accuracy                           0.47       114
   macro avg       0.47      0.47      0.47       114
weighted avg       0.47      0.47      0.47       114



In [55]:
accuracy = accuracy_score(y_test, predictions)
accuracy

0.47368421052631576

## Frequency Domain

In [39]:
def loading_data_freq(path):
  x = []
  y = []
  for brand in os.listdir(path):
    images = os.listdir(path + '/' + brand)
    for image in images:
      im = Image.open(path + '/' + brand + '/' + image)
      resize = im.resize((200,200))
      np_img = np.fft.fftshift(resize)
      # data = np.asarray(im)
      np_img = np_img.flatten()
      x.append(np_img)
      y.append(os.listdir(path).index(brand))
      #im.show()
  return x, y

In [40]:
X_train, y_train = loading_data_freq(train_path)

In [47]:
X_test, y_test = loading_data_freq(test_path)

## Navie Bayes

In [48]:
nb = GaussianNB()

In [49]:
param = {'var_smoothing': np.logspace(0,-9, num=20)}

In [50]:
grid = GridSearchCV(nb, param)

In [51]:
grid.fit(X_train, y_train)

GridSearchCV(estimator=GaussianNB(),
             param_grid={'var_smoothing': array([1.00000000e+00, 3.35981829e-01, 1.12883789e-01, 3.79269019e-02,
       1.27427499e-02, 4.28133240e-03, 1.43844989e-03, 4.83293024e-04,
       1.62377674e-04, 5.45559478e-05, 1.83298071e-05, 6.15848211e-06,
       2.06913808e-06, 6.95192796e-07, 2.33572147e-07, 7.84759970e-08,
       2.63665090e-08, 8.85866790e-09, 2.97635144e-09, 1.00000000e-09])})

In [52]:
print(grid.best_params_)

{'var_smoothing': 1.0}


In [53]:
nb = GaussianNB(var_smoothing= 1.0)

In [54]:
nb.fit(X_train, y_train)

GaussianNB(var_smoothing=1.0)

In [55]:
predictions = nb.predict(X_test)
predictions

array([2, 1, 2, 1, 1, 2, 2, 1, 1, 1, 1, 1, 2, 2, 2, 1, 2, 1, 1, 2, 2, 1,
       1, 2, 2, 1, 2, 1, 1, 1, 1, 2, 1, 1, 2, 2, 1, 1, 1, 2, 1, 2, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 2, 1, 1, 1, 2, 2, 1, 1, 2, 2, 2, 1, 1, 2,
       2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 2, 2, 1, 1, 2, 0, 2, 1, 1,
       1, 1, 1, 1, 1, 2, 0, 1, 2, 1, 2, 2, 1, 1, 1, 2, 2, 2, 1, 1, 2, 2,
       1, 2, 1, 2])

In [56]:
print(classification_report(y_test, predictions))

              precision    recall  f1-score   support

           0       0.00      0.00      0.00        38
           1       0.37      0.66      0.48        38
           2       0.36      0.42      0.39        38

    accuracy                           0.36       114
   macro avg       0.25      0.36      0.29       114
weighted avg       0.25      0.36      0.29       114



In [57]:
accuracy = accuracy_score(y_test, predictions)
accuracy

0.35964912280701755

### Logistic Regression

In [60]:
logmodel = LogisticRegression()

In [61]:
param = {'max_iter': [50,100,150,200],
          'penalty':["l1","l2"]}

In [62]:
grid = GridSearchCV(logmodel, param)

In [63]:
grid.fit(X_train, y_train)

c:\Users\Samuels\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: 
Traceback (most recent call last):
  File "c:\Users\Samuels\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py", line 593, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "c:\Users\Samuels\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py", line 1306, in fit
    solver = _check_solver(self.solver, self.penalty, self.dual)
  File "c:\Users\Samuels\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py", line 443, in _check_solver
    raise ValueError("Solver %s supports only 'l2' or 'none' penalties, "
ValueError: Solver lbfgs supports only 'l2' or 'none' penalties, got l1 penalty.

  warnings.warn("Estimator fit failed. The score on this train-test"
c:\Users\Samuels\anaconda3\lib\site-packages\sklearn\model_se

GridSearchCV(estimator=LogisticRegression(),
             param_grid={'max_iter': [50, 100, 150, 200],
                         'penalty': ['l1', 'l2']})

In [64]:
print(grid.best_params_)

{'max_iter': 200, 'penalty': 'l2'}


In [65]:
logmodel = LogisticRegression(max_iter=200, penalty = 'l2').fit(X_train, y_train)

c:\Users\Samuels\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [66]:
predictions = logmodel.predict(X_test)
predictions

array([1, 1, 2, 2, 1, 0, 2, 2, 1, 0, 1, 2, 2, 0, 1, 1, 2, 1, 1, 2, 1, 1,
       2, 2, 1, 0, 2, 1, 2, 2, 2, 0, 0, 2, 0, 2, 2, 2, 2, 0, 2, 2, 1, 2,
       2, 1, 0, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 1, 2, 0, 1, 0, 0, 1, 2, 0,
       0, 1, 2, 0, 2, 0, 1, 1, 2, 2, 0, 2, 0, 0, 0, 0, 2, 0, 0, 1, 0, 0,
       1, 1, 2, 1, 1, 0, 1, 2, 0, 1, 1, 0, 1, 2, 1, 0, 1, 0, 0, 2, 1, 0,
       1, 0, 1, 0])

In [67]:
print(classification_report(y_test, predictions))

              precision    recall  f1-score   support

           0       0.20      0.18      0.19        38
           1       0.23      0.21      0.22        38
           2       0.14      0.16      0.15        38

    accuracy                           0.18       114
   macro avg       0.19      0.18      0.19       114
weighted avg       0.19      0.18      0.19       114



In [68]:
accuracy = accuracy_score(y_test, predictions)
accuracy

0.18421052631578946